---
dpdk_interface: ens15f1
dpdk_max_ring_buffer_size: 8160
dpdk_mtu: 9216
dpdk_vlan: 801
dpdk_du_u_plane_mac: "00:11:22:33:44:66"
dpdk_du_c_plane_mac: "00:11:22:33:44:67"
dpdk_u_plane_pci: "0000:3a:09.0"
dpdk_c_plane_pci: "0000:3a:09.1"
dpdk_driver: vfio-pci
sriovNetworkNamespace: sriov-network-operator
sriovResourceNameCplane: ruvfioc
sriovResourceNameUplane: ruvfiou
dpdk_interface_c: ens15f1#0-1
dpdk_interface_u: ens15f1#2-3
pci_dpdk_interface: "0000:3a:00.1"
