---
# Defaults for all hosts in group 'ran_node'
ran_sopnode: sopnode-f3

# RT Ubuntu runs as root only
ansible_user: root

# PTP
ptp_interface: ens15f2
ptp_domain_number: 24

# DPDK NIC and tuning
dpdk_interface: ens15f2
dpdk_max_ring_buffer_size: 8160
dpdk_mtu: 9216 # was 9600
dpdk_vlan: 3 # 801 for benetel1, 802 for benetel2, 3 is benetel default

dpdk_du_u_plane_mac: "00:11:22:33:44:66"
dpdk_du_c_plane_mac: "00:11:22:33:44:67"
dpdk_u_plane_pci: "0000:3a:11.0"
dpdk_c_plane_pci: "0000:3a:11.1"
dpdk_driver: "vfio-pci"

sriovNetworkNamespace: "sriov-network-operator"
sriovResourceNameCplane: "ruvfioc"
sriovResourceNameUplane: "ruvfiou"

dpdk_interface_c: ens15f2#0-1
dpdk_interface_u: ens15f2#2-3
pci_dpdk_interface: "0000:3a:00.2" # retrieved with dmesg |grep ens15f2 on sopnode-f3



