---
# to remove (now in group_vars/ran_node.yml)
#dpdk_interface: ens15f1
#dpdk_max_ring_buffer_size: 8160
#dpdk_mtu: 9216 # was 9600
#dpdk_vlan: 801
#dpdk_du_u_plane_mac: "00:11:22:33:44:66"
#dpdk_du_c_plane_mac: "00:11:22:33:44:67"
#dpdk_u_plane_pci: "0000:3a:11.0"
#dpdk_c_plane_pci: "0000:3a:11.1"
#dpdk_driver: "vfio-pci"


