apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: oail1
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 10s

    route:
      receiver: 'default'
      group_wait: 1s
      group_interval: 5s
      repeat_interval: 10m

    receivers:
      - name: 'default'
        webhook_configs:
          - url: "http://138.96.245.50:5000/alert"
