- name: Define list of inventory booleans to normalize
  set_fact:
    inventory_booleans:
      - fhi72
      - aw2s
      - f1f2_ran
      - f3_ran
      - bridge_enabled
      - monitoring_enabled

- name: Force inventory booleans to real booleans
  set_fact:
    "{{ item }}": "{{ hostvars[inventory_hostname][item] | bool }}"
  loop: "{{ inventory_booleans }}"

- name: Debug normalized booleans
  debug:
    msg: "{{ item }} = {{ hostvars[inventory_hostname][item] }}"
  loop: "{{ inventory_booleans }}"
