---
# This role only works for Open5gs core...

- name: Include 5G profile variables
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../group_vars/all/5g_profile_{{ fiveg_profile | default('default') }}.yaml"
    name: fiveg

- name: Retrieve UPF1/UPF2 IPs from slices prefix
  set_fact:
    upf1_ip: >-
      {{
        (fiveg.slices
        | selectattr('name', 'equalto', 'slice1')
        | map(attribute='ip_prefix')
        | first) ~ '.1'
      }}
    upf2_ip: >-
      {{
        (fiveg.slices
        | selectattr('name', 'equalto', 'slice2')
        | map(attribute='ip_prefix')
        | first) ~ '.1'
      }}
	
- name: Get list of UPF pods
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: open5gs
  register: upf_pods
  no_log: true

- set_fact:
    upf1_pod: "{{ item.metadata.name }}"
  loop: "{{ upf_pods.resources }}"
  when: item.metadata.name is match('^open5gs-upf1-')
  no_log: true

- set_fact:
    upf2_pod: "{{ item.metadata.name }}"
  loop: "{{ upf_pods.resources }}"
  when: item.metadata.name is match('^open5gs-upf2-')
  no_log: true

- name: Wait for UPF1 pod to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: open5gs
    name: "{{ upf1_pod }}"
  register: upf1_status
  until: upf1_status.resources[0].status.containerStatuses[0].ready
  retries: 20
  delay: 5

- name: Wait for UPF2 pod to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: open5gs
    name: "{{ upf2_pod }}"
  register: upf2_status
  until: upf2_status.resources[0].status.containerStatuses[0].ready
  retries: 20
  delay: 5

- name: Install iperf3 on UPF1
  shell: |
    kubectl -n open5gs exec {{ upf1_pod }} -- bash -c '
      set -euo pipefail
      if ! command -v iperf3 >/dev/null 2>&1; then
        apt-get update -qq &&
        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq iperf3
      fi
    '
  register: upf1_install
  changed_when: "'Preparing to unpack' in upf1_install.stdout"

- name: Install iperf3 on UPF2
  shell: |
    kubectl -n open5gs exec {{ upf2_pod }} -- bash -c '
      set -euo pipefail
      if ! command -v iperf3 >/dev/null 2>&1; then
        apt-get update -qq &&
        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq iperf3
      fi
    '
  register: upf2_install
  changed_when: "'Preparing to unpack' in upf2_install.stdout"

# - name: Stop any potential existing background iperfs running on UPF1
#   shell: |
#     kubectl -n open5gs exec {{ upf1_pod }} -- bash -c 'pkill iperf3'
#   ignore_errors: true

# - name: Stop any potential existing background iperfs running on UPF2
#   shell: |
#     kubectl -n open5gs exec {{ upf2_pod }} -- bash -c 'pkill iperf3'
#   ignore_errors: true

- name: Start first iperf3 server on UPF1 (background)
  shell: |
    kubectl -n open5gs exec {{ upf1_pod }} -- bash -c 'iperf3 -s -B {{ upf1_ip }} -D'

- name: Start second iperf3 server on UPF1 (background)
  shell: |
    kubectl -n open5gs exec {{ upf1_pod }} -- bash -c 'iperf3 -s -B {{ upf1_ip }} -p 5202 -D'

- name: Start first iperf3 server on UPF2 (background)
  shell: |
    kubectl -n open5gs exec {{ upf2_pod }} -- bash -c 'iperf3 -s -B {{ upf1_ip }} -D'

- name: Start second iperf3 server on UPF2 (background)
  shell: |
    kubectl -n open5gs exec {{ upf2_pod }} -- bash -c 'iperf3 -s -B {{ upf2_ip }} -p 5202 -D'
