---
- name: Remove NoSchedule taint from control-plane node
  ansible.builtin.command: >
    kubectl taint nodes {{ inventory_hostname }} node-role.kubernetes.io/control-plane:NoSchedule-
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: taint_result
  failed_when: false # ignore possible error
  changed_when: "'untainted' in taint_result.stdout"



