# Active profile, can be overrided via -e ou inventory
5g_profile: default

# Load the right 5G profile
5g_config: "{{ lookup('file', 'group_vars/all/5g_profiles/' + 5g_profile + '.yaml') | from_yaml }}"


# How to use...

#- name: Configure slices
#  debug:
#    msg: "DNN={{ item.dnn }} SST={{ item.sst }} SD={{ item.sd }}"
#  loop: "{{ 5g_config.slices }}"

#MCC={{ 5g_config.plmn.mcc }}
#MNC={{ 5g_config.plmn.mnc }}
#TAC={{ 5g_config.plmn.tac }}

## Change profile
#ansible-playbook deploy.yml -e 5g_profile=lab

# or in inventory

#[all:vars]
#5g_profile=lab

