plmn:
  mcc: "001"
  mnc: "01"
  tac: "1"

dnns:
  - name: streaming
    pdu_type: IPV4
  - name: internet
    pdu_type: IPV4
  - name: ims
    pdu_type: IPV4V6

slices:
  - name: slice1
    dnn: internet
    sst: "1"
    sd: "EMPTY"
    qos:
      five_qi: "9"
      arp:
        priority_level: "8"
        preempt_cap: "NOT_PREEMPT"
        preempt_vuln: "PREEMPTABLE"
      priority_level: "1"
    bandwidth:
      uplink: "20Mbps"
      downlink: "40Mbps"
    ip_prefix: "12.1.1"

  - name: slice2
    dnn: streaming
    sst: "1"
    sd: "000001"
    qos:
      five_qi: "5"
      arp:
        priority_level: "1"
        preempt_cap: "NOT_PREEMPT"
        preempt_vuln: "PREEMPTABLE"
      priority_level: "1"
    bandwidth:
      uplink: "100Mbps"
      downlink: "200Mbps"
    ip_prefix: "14.1.1"

security:
  full_key: "fec86ba6eb707ed08905757b1bb44b8f"
  opc: "C42449363BBAD02B66D16BC975D77CC1"

ues:
  qhat01:
    imsi_suffix: "0000000006"
    slice: slice1
  qhat02:
    imsi_suffix: "0000000007"
    slice: slice2
  qhat03:
    imsi_suffix: "0000000008"
    slice: slice1
  qhat10:
    imsi_suffix: "0000000009"
    slice: slice1
  qhat11:
    imsi_suffix: "0000000010"
    slice: slice1
  qhat20:
    imsi_suffix: "0000000011"
    slice: slice1
  qhat21:
    imsi_suffix: "0000000012"
    slice: slice1
  qhat22:
    imsi_suffix: "0000000013"
    slice: slice1
  qhat23:
    imsi_suffix: "0000000014"
    slice: slice1
  UE18:
    imsi_suffix: "000001121"  # used for OAI RFSIM UE
    slice: slice1
  UE19:
    imsi_suffix: "000001122"  # used for OAI RFSIM UE2
    slice: slice2
  UE20:
    imsi_suffix: "000001123"  # used for OAI RFSIM UE3
    slice: slice1

