# kubeadm-config.yaml

# Kubelet configuration
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
cpuManagerPolicy: static
cpuManagerPolicyOptions:
  "full-pcpus-only": "true"
reservedSystemCPUs: 0-5
topologyManagerPolicy: "best-effort"
failSwapOn: false
containerLogMaxSize: 50Mi
featureGates:
  CPUManager: true
  CPUManagerPolicyOptions: true
  CPUManagerPolicyBetaOptions: true
memorySwap: {}

---

# Cluster configuration
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  podSubnet: "10.244.0.0/16" # your pod network CIDR
# Optional: add extraClusterConfig for control plane tweaks
