---
repo_url: "https://github.com/turletti/srsran-helm.git"
version: main

ran_ns: {{ core }}

repo_dest: "~/srsran-helm"

srs_gnb_label_selectors:
  - "app=srsran"
  - "component=gnb"

srs_ue_label_selectors:
  - "app=srsran"
  - "component=ue"

ue_count: 3

kubectl_bin: "/usr/bin/kubectl"

yq_version: "v4.45.1"
yq_bin_path: "/usr/local/bin/yq"
yq_url: "https://github.com/mikefarah/yq/releases/download/{{ yq_version }}/yq_linux_amd64"
