---
- name: Install VNC Server on {{ fit_node }}
  shell: ssh root@{{ fit_node }} 'apt update && apt install -y tigervnc-standalone-server tigervnc-xorg-extension tigervnc-viewer'
  delegate_to: faraday.inria.fr
  ignore_errors: true

- name: Set VNC password non-interactively
  shell: |
    ssh root@{{ fit_node }} "mkdir -p /root/.vnc && \
    echo '1234567890' | vncpasswd -f > /root/.vnc/passwd && \
    chmod 600 /root/.vnc/passwd"
  delegate_to: faraday.inria.fr

- name: Launch VNC server on {{ fit_node }}
  shell: ssh root@{{ fit_node }} 'vncserver'
  delegate_to: faraday.inria.fr

- name: Launch uhd_fft inside xterm on {{ fit_node }}
  shell: ssh root@{{ fit_node }} "nohup env DISPLAY=:1 xterm -e 'uhd_fft -f {{ hostvars[groups['faraday'][0]].freq }} -s 50M; bash' >/dev/null 2>&1 &"
  delegate_to: faraday.inria.fr
