# Nodes live images
pos_image: ubuntu-jammy-slices@2025-04-02T01:33:28+00:00
pos_rt_image: ubuntu-questing-rt@2025-10-29T19:34:30+00:00

# Boot parameters for nodes without core tuning 
boot_parameters: >-
  biosdevname=0 net.ifnames=0 mitigations=off intel_iommu=on iommu=pt
  selinux=0 enforcing=0 nosoftlockup intel_pstate=disable idle=poll nosmt

# Boot parameters tuned to support USRP N3XX and AW2S RRUs
boot_ran_parameters: >-
  biosdevname=0 net.ifnames=0 mitigations=off intel_iommu=on iommu=pt
  selinux=0 enforcing=0 isolcpus=managed_irq,16-63
  nohz_full=16-63 nohz=on rcu_nocbs=16-63
  kthread_cpus=0-4 irqaffinity=0-4 rcu_nocb_poll
  nosoftlockup intel_pstate=disable idle=poll skew_tick=1
  tsc=nowatchdog nmi_watchdog=0 softlockup_panic=0 audit=0 nosmt

# Boot parameters tuned for RT sopnode-f3 to support Benetel RRUs
boot_parameters_rt_f3: >-
  net.ifnames=1 biosdevname=0 isolcpus=managed_irq,6-63 nohz_full=6-63
  nohz=on rcu_nocbs=6-63 kthread_cpus=0-5 irqaffinity=0-5 rcu_nocb_poll
  selinux=0 enforcing=0 crashkernel=auto intel_pstate=disable nosoftlockup
  hugepagesz=1G hugepages=40 hugepagesz=2M hugepages=0 default_hugepagesz=1G
  mitigations=off intel_iommu=on processor.max_cstate=1 idle=poll
  intel_idle.max_cstate=0 iommu=pt skew_tick=1 tsc=nowatchdog
  nmi_watchdog=0 softlockup_panic=0 audit=0 mce=off nosmt

