pos_image: ubuntu-jammy-slices@2025-04-02T01:33:28+00:00
pos_rt_image: ubuntu-questing-rt@2025-10-29T18:20:50+00:00
# Boot parameters for ran node on f1 or f2 with USRP N3XX or AW2S RRUs
boot_parameters_f1f2: >-
  biosdevname=0 net.ifnames=0 mitigations=off intel_iommu=on iommu=pt
  selinux=0 enforcing=0 isolcpus=managed_irq,16-63 nohz_full=16-63
  nohz=on rcu_nocbs=16-63 kthread_cpus=0-3 irqaffinity=0-3 rcu_nocb_poll
  nosoftlockup intel_pstate=disable idle=poll skew_tick=1 tsc=nowatchdog
  nmi_watchdog=0 softlockup_panic=0 audit=0
# Boot parameters for ran node on f3 with USRP N3XX or AW2S RRUs
boot_parameters_f3: >-
  biosdevname=0 net.ifnames=0 mitigations=off intel_iommu=on iommu=pt
  selinux=0 enforcing=0 isolcpus=managed_irq,16-63,80-127
  nohz_full=16-63,80-127 nohz=on rcu_nocbs=16-63,80-127
  kthread_cpus=0-15,64-79 irqaffinity=0-15,64-79 rcu_nocb_poll
  nosoftlockup intel_pstate=disable idle=poll skew_tick=1
  tsc=nowatchdog nmi_watchdog=0 softlockup_panic=0 audit=0
# Boot parameters for ran node on rt ubuntu for Benetel RRUs
boot_parameters_rt: >-
  isolcpus=managed_irq,6-63 nohz_full=6-63 nohz=on rcu_nocbs=6-63
  kthread_cpus=0-5 irqaffinity=0-5 rcu_nocb_poll selinux=0 enforcing=0
  crashkernel=auto intel_pstate=disable nosoftlockup hugepagesz=1G
  hugepages=40 hugepagesz=2M hugepages=0 default_hugepagesz=1G
  mitigations=off intel_iommu=on processor.max_cstate=1 idle=poll
  intel_idle.max_cstate=0 iommu=pt skew_tick=1 tsc=nowatchdog
  nmi_watchdog=0 softlockup_panic=0 audit=0 mce=off nosmt

