---
repo_url: "https://github.com/sopnode/oai5g-rru.git"
repo_dest: "~/oai5g-rru"
core_ns: oai5g
epo_oai5g_rru: "https://github.com/sopnode/oai5g-rru.git"
tag_oai5g_rru: "{{ 'benetel' if fhi72 else 'gen-cn2' }}"
repo_oai_cn5g_fed: "https://gitlab.eurecom.fr/oai/cn5g/oai-cn5g-fed.git"
tag_oai_cn5g_fed: "{{ 'fhi72-r2lab' if fhi72 else 'gen-cn2' }}"
conf: "{{ hostvars[groups['faraday'][0]].conf }}"
prepare_demo: "{{ repo_dest }}/prepare-demo-oai.sh"
demo_oai: "{{ repo_dest }}/demo-oai.sh"
charts_base: "{{ repo_dest }}/oai-cn5g-fed/charts/oai-5g-ran"
