---
ptp_domain_number: 24
ptp_slave_only: 1
ptp_time_stamping: hardware
ptp_tx_timestamp_timeout: 100
ptp_logging_level: 6
ptp_summary_interval: 0
ptp_log_announce_interval: 1
ptp_log_sync_interval: -4
ptp_verbose: 1
ptp_interface: ens15f2
ptp_network_transport: L2


