---
- name: Update apt cache and install Kubernetes components
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes
  become: true

- name: Ensure kube-proxy config is set
  copy:
    dest: /etc/kubernetes/kubeproxy-config.yaml
    content: |
      apiVersion: kubeproxy.config.k8s.io/v1alpha1
      kind: KubeProxyConfiguration
      ipvs:
        strictARP: true
  when: rru in ['jaguar', 'panther']