---
- name: Remove taint from node {{ target_node }}
  ansible.builtin.command: >
    kubectl taint node {{ target_node }} test-eviction=true:NoSchedule-
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: taint_out
  failed_when: >
    taint_out.rc != 0 and
    'not found' not in taint_out.stderr
  changed_when: >
    'untainted' in taint_out.stdout



