---
# Connect only the first UE 
- name: Connect first UE on R2Lab to 5G network
  hosts: faraday
  tasks:
    - name: Connect first UE on R2Lab to 5G network
      include_role:
        name: r2lab/ue/connect
      vars:
        ue: "{{ groups['qhats'][0] }}"
