---
- hosts: faraday
  tasks:
    - name: Connect UEs on R2Lab to 5G network
      include_role:
        name: r2lab/ue/connect
      vars:
        ue_item: "{{ item }}"
      loop: "{{ groups['qhats'] }}"
      loop_control:
        label: "{{ item }}"
      ignore_errors: true
