---
repo_url: "https://github.com/yassir63/open5gs-k8s.git"
repo_dest: "~/open5gs-k8s"
ran_ns: open5gs
script_path: "{{ repo_dest }}/oai-ran/prepare-demo-oai.sh"
charts_base: "{{ repo_dest }}/oai-ran/oai-cn5g-fed/charts/oai-5g-core"
