---
# Open5GS namespace
open5gs_ns: open5gs

# Open5gs repo directory
repo_dest: "~/open5gs-k8s"

# Deployment option, can be overrided with -e deployment_option
deployment_option: "msd/overlays/open5gs-metrics"

nfs:
  - nrf
  - scp
  - amf
  - udr
  - bsf
  - ausf
  - nssf
  - pcf
  - udm

nad_list:
  - n2network
  - n3network
  - n4network
  